#define  TAIR_RETURN_SUCCESS 0

#define  TAIR_RETURN_PROXYED -4000
#define  TAIR_RETURN_FAILED -3999
#define  TAIR_RETURN_DATA_NOT_EXIST -3998
#define  TAIR_RETURN_VERSION_ERROR -3997
#define  TAIR_RETURN_TYPE_NOT_MATCH -3996

#define  TAIR_RETURN_PLUGIN_ERROR -3995
#define  TAIR_RETURN_SERIALIZE_ERROR -3994
#define  TAIR_RETURN_ITEM_EMPTY -3993
#define  TAIR_RETURN_OUT_OF_RANGE -3992
#define  TAIR_RETURN_ITEMSIZE_ERROR -3991

#define  TAIR_RETURN_SEND_FAILED -3990
#define  TAIR_RETURN_TIMEOUT -3989
#define  TAIR_RETURN_DATA_EXPIRED -3988
#define  TAIR_RETURN_SERVER_CAN_NOT_WORK -3987
#define  TAIR_RETURN_WRITE_NOT_ON_MASTER -3986

#define  TAIR_RETURN_DUPLICATE_BUSY -3985
#define  TAIR_RETURN_MIGRATE_BUSY -3984

#define  TAIR_RETURN_PARTIAL_SUCCESS -3983
#define  TAIR_RETURN_INVALID_ARGUMENT -3982
#define  TAIR_RETURN_CANNOT_OVERRIDE -3981